apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: gathering-nike
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: server
      src: "."
      ports:
       - name: http
         port: 8080
      publicPort: http
      ingressConfiguration:
        - websocketfriendly
  dnsAppAlias:
    environment: prod
    component: server
